/**
 * @agenc/runtime - Agent runtime infrastructure for AgenC
 *
 * This is the main entry point for the @agenc/runtime package.
 * It re-exports all public APIs including agent management, types,
 * utilities, and key constants from @agenc/sdk.
 *
 * @packageDocumentation
 */

// Re-export SDK constants for convenience
export {
  PROGRAM_ID,
  PRIVACY_CASH_PROGRAM_ID,
  DEVNET_RPC,
  MAINNET_RPC,
  SEEDS,
  HASH_SIZE,
  RESULT_DATA_SIZE,
  U64_SIZE,
  DISCRIMINATOR_SIZE,
  OUTPUT_FIELD_COUNT,
  PROOF_SIZE_BYTES,
  VERIFICATION_COMPUTE_UNITS,
  PUBLIC_INPUTS_COUNT,
  PERCENT_BASE,
  DEFAULT_FEE_PERCENT,
  BPS_BASE,
  BID_ID_MAX_LENGTH,
  MARKETPLACE_ID_PATTERN,
  DEFAULT_WEIGHTED_SCORE_WEIGHTS,
  canonicalizeMarketplaceId,
  validateMarketplaceId,
  isValidBps,
  TaskState,
  type TaskStatus,
} from '@agenc/sdk';

// IDL and program creation
export {
  IDL,
  type AgencCoordination,
  createProgram,
  createReadOnlyProgram,
} from './idl.js';

export const VERSION = '0.1.0';

// Runtime class
export { AgentRuntime } from './runtime.js';

// Types (protocol, errors, wallet, config) — all via types barrel
export {
  // Protocol types
  ProtocolConfig,
  parseProtocolConfig,
  MAX_MULTISIG_OWNERS,
  // Error constants
  RuntimeErrorCodes,
  AnchorErrorCodes,
  // Error types
  type RuntimeErrorCode,
  type AnchorErrorCode,
  type AnchorErrorName,
  type ParsedAnchorError,
  // Error classes
  RuntimeError,
  AgentNotRegisteredError,
  AgentAlreadyRegisteredError,
  ValidationError,
  RateLimitError,
  InsufficientStakeError,
  ActiveTasksError,
  PendingDisputeVotesError,
  RecentVoteActivityError,
  TaskNotFoundError,
  TaskNotClaimableError,
  TaskExecutionError,
  TaskSubmissionError,
  ExecutorStateError,
  TaskTimeoutError,
  // Error helper functions
  isAnchorError,
  parseAnchorError,
  getAnchorErrorName,
  getAnchorErrorMessage,
  isRuntimeError,
  // Agent constants
  AgentCapabilities,
  AGENT_REGISTRATION_SIZE,
  AGENT_ID_LENGTH,
  MAX_ENDPOINT_LENGTH,
  MAX_METADATA_URI_LENGTH,
  MAX_REPUTATION,
  MAX_U8,
  CAPABILITY_NAMES,
  // Agent enum
  AgentStatus,
  // Agent functions
  agentStatusToString,
  isValidAgentStatus,
  hasCapability,
  getCapabilityNames,
  createCapabilityMask,
  parseAgentState,
  computeRateLimitState,
  // PDA derivation helpers
  deriveAgentPda,
  deriveProtocolPda,
  findAgentPda,
  findProtocolPda,
  deriveAuthorityVotePda,
  findAuthorityVotePda,
  // Event subscriptions
  subscribeToAgentRegistered,
  subscribeToAgentUpdated,
  subscribeToAgentDeregistered,
  subscribeToAgentSuspended,
  subscribeToAgentUnsuspended,
  subscribeToAllAgentEvents,
  // AgentManager class
  AgentManager,
  // Agent types
  type AgentCapability,
  type CapabilityName,
  type AgentState,
  type AgentRegistrationParams,
  type AgentUpdateParams,
  type RateLimitState,
  type AgentRegisteredEvent,
  type AgentUpdatedEvent,
  type AgentDeregisteredEvent,
  type AgentSuspendedEvent,
  type AgentUnsuspendedEvent,
  // PDA types
  type PdaWithBump,
  // Event types
  type AgentEventCallback,
  type EventSubscription,
  type AgentEventCallbacks,
  type EventSubscriptionOptions,
  // AgentManager types
  type AgentManagerConfig,
  type ProtocolConfigCacheOptions,
  type GetProtocolConfigOptions,
  // Wallet types and helpers
  type Wallet,
  type SignMessageWallet,
  KeypairFileError,
  ensureWallet,
  keypairToWallet,
  loadKeypairFromFile,
  loadKeypairFromFileSync,
  getDefaultKeypairPath,
  loadDefaultKeypair,
  // AgentRuntime types
  type AgentRuntimeConfig,
  isKeypair,
  // Task constants (Phase 3)
  TASK_ID_LENGTH,
  // Task enums
  OnChainTaskStatus,
  // Task functions
  taskStatusToString,
  taskTypeToString,
  parseTaskStatus,
  parseTaskType,
  parseOnChainTask,
  parseOnChainTaskClaim,
  isPrivateTask,
  isTaskExpired,
  isTaskClaimable,
  isPrivateExecutionResult,
  // Task PDA derivation
  deriveTaskPda,
  findTaskPda,
  deriveClaimPda,
  findClaimPda,
  deriveEscrowPda,
  findEscrowPda,
  // Task types
  type OnChainTask,
  type OnChainTaskClaim,
  type RawOnChainTask,
  type RawOnChainTaskClaim,
  type TaskExecutionContext,
  type TaskExecutionResult,
  type PrivateTaskExecutionResult,
  type TaskHandler,
  type DiscoveredTask,
  type TaskFilterConfig,
  type TaskScorer,
  type TaskDiscoveryConfig,
  type TaskOperationsConfig,
  type ClaimResult,
  type CompleteResult,
  type TaskExecutorConfig,
  type TaskExecutorEvents,
  type OperatingMode,
  type BatchTaskItem,
  type TaskExecutorStatus,
  // Config migration
  CURRENT_CONFIG_VERSION,
  KNOWN_CONFIG_KEYS,
  DEPRECATED_KEYS,
  ConfigMigrationError,
  configVersionToString,
  parseConfigVersion,
  compareVersions,
  migrateConfig,
  validateConfigStrict,
  buildConfigSchemaSnapshot,
  type ConfigVersion,
  type ConfigMigrationFn,
  type ConfigMigrationStep,
  type ConfigWarning,
  type ConfigValidationResult,
  type ConfigSchemaSnapshot,
} from './types/index.js';

// Task module (Phase 3)
export {
  // TaskOperations class
  TaskOperations,
  type TaskOpsConfig,
  // Task filter functions
  matchesFilter,
  hasRequiredCapabilities,
  defaultTaskScorer,
  rankTasks,
  filterAndRank,
  // TaskDiscovery class
  TaskDiscovery,
  type TaskDiscoveryOptions,
  type TaskDiscoveryResult,
  type TaskDiscoveryListener,
  type TaskDiscoveryMode,
  // TaskExecutor class
  TaskExecutor,
} from './task/index.js';

// Logger utilities
export {
  Logger,
  LogLevel,
  createLogger,
  silentLogger,
} from './utils/index.js';

// Encoding utilities
export {
  generateAgentId,
  hexToBytes,
  bytesToHex,
  agentIdFromString,
  agentIdToString,
  agentIdToShortString,
  agentIdsEqual,
  lamportsToSol,
  solToLamports,
  bigintsToProofHash,
  proofHashToBigints,
  toAnchorBytes,
} from './utils/index.js';

// Validation utilities
export {
  type ValidationResult,
  validationResult,
  requireNonEmptyString,
  requireFiniteNumber,
  requireOneOf,
  requireIntRange,
} from './utils/index.js';

// SPL Token utilities
export {
  isTokenTask,
  buildCompleteTaskTokenAccounts,
  buildResolveDisputeTokenAccounts,
  buildExpireDisputeTokenAccounts,
  buildApplyDisputeSlashTokenAccounts,
  buildCreateTaskTokenAccounts,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from './utils/index.js';

// Event monitoring (Phase 2)
export {
  // Shared types
  type EventCallback,

  // Enums
  TaskType,
  ResolutionType,
  RateLimitActionType,
  RateLimitType,

  // Task events
  type TaskCreatedEvent,
  type TaskClaimedEvent,
  type TaskCompletedEvent,
  type TaskCancelledEvent,
  type DependentTaskCreatedEvent,
  type TaskEventCallbacks,
  type TaskEventFilterOptions,
  subscribeToTaskCreated,
  subscribeToTaskClaimed,
  subscribeToTaskCompleted,
  subscribeToTaskCancelled,
  subscribeToDependentTaskCreated,
  subscribeToAllTaskEvents,

  // Dispute events
  type DisputeInitiatedEvent,
  type DisputeVoteCastEvent,
  type DisputeResolvedEvent,
  type DisputeExpiredEvent,
  type DisputeCancelledEvent,
  type ArbiterVotesCleanedUpEvent,
  type DisputeEventCallbacks,
  type DisputeEventFilterOptions,
  subscribeToDisputeInitiated,
  subscribeToDisputeVoteCast,
  subscribeToDisputeResolved,
  subscribeToDisputeExpired,
  subscribeToDisputeCancelled,
  subscribeToArbiterVotesCleanedUp,
  subscribeToAllDisputeEvents,

  // Protocol events
  type StateUpdatedEvent,
  type ProtocolInitializedEvent,
  type RewardDistributedEvent,
  type RateLimitHitEvent,
  type MigrationCompletedEvent,
  type ProtocolVersionUpdatedEvent,
  type RateLimitsUpdatedEvent,
  type ProtocolFeeUpdatedEvent,
  type ReputationChangedEvent,
  type BondDepositedEvent,
  type BondLockedEvent,
  type BondReleasedEvent,
  type BondSlashedEvent,
  type SpeculativeCommitmentCreatedEvent,
  type ProtocolEventCallbacks,
  type ProtocolEventFilterOptions,
  subscribeToStateUpdated,
  subscribeToProtocolInitialized,
  subscribeToRewardDistributed,
  subscribeToRateLimitHit,
  subscribeToMigrationCompleted,
  subscribeToProtocolVersionUpdated,
  subscribeToRateLimitsUpdated,
  subscribeToProtocolFeeUpdated,
  subscribeToReputationChanged,
  subscribeToBondDeposited,
  subscribeToBondLocked,
  subscribeToBondReleased,
  subscribeToBondSlashed,
  subscribeToSpeculativeCommitmentCreated,
  subscribeToAllProtocolEvents,

  // Parse functions
  parseTaskCreatedEvent,
  parseTaskClaimedEvent,
  parseTaskCompletedEvent,
  parseTaskCancelledEvent,
  parseDisputeInitiatedEvent,
  parseDisputeVoteCastEvent,
  parseDisputeResolvedEvent,
  parseDisputeExpiredEvent,
  parseDisputeCancelledEvent,
  parseArbiterVotesCleanedUpEvent,
  parseStateUpdatedEvent,
  parseProtocolInitializedEvent,
  parseRewardDistributedEvent,
  parseRateLimitHitEvent,
  parseMigrationCompletedEvent,
  parseProtocolVersionUpdatedEvent,
  parseRateLimitsUpdatedEvent,
  parseProtocolFeeUpdatedEvent,
  parseReputationChangedEvent,
  parseBondDepositedEvent,
  parseBondLockedEvent,
  parseBondReleasedEvent,
  parseBondSlashedEvent,
  parseSpeculativeCommitmentCreatedEvent,
  parseDependentTaskCreatedEvent,

  // EventMonitor
  EventMonitor,
  type EventMonitorConfig,
  type EventMonitorMetrics,
} from './events/index.js';

// Skill library system
export {
  // Core types
  type Skill,
  type SkillMetadata,
  type SkillAction,
  type SkillContext,
  type SemanticVersion,
  type SkillRegistryConfig,
  SkillState,
  // Error types
  SkillNotFoundError,
  SkillNotReadyError,
  SkillActionNotFoundError,
  SkillInitializationError,
  SkillAlreadyRegisteredError,
  // Registry
  SkillRegistry,
  // Jupiter skill
  JupiterSkill,
  JupiterClient,
  JupiterApiError,
  type JupiterSkillConfig,
  type SwapQuoteParams,
  type SwapQuote,
  type SwapResult,
  type TokenBalance,
  type TransferSolParams,
  type TransferTokenParams,
  type TransferResult,
  type TokenPrice,
  type TokenMint,
  JUPITER_API_BASE_URL,
  JUPITER_PRICE_API_URL,
  WSOL_MINT,
  USDC_MINT,
  USDT_MINT,
  WELL_KNOWN_TOKENS,
  // Markdown SKILL.md parser
  type MarkdownSkill,
  type MarkdownSkillMetadata,
  type SkillRequirements,
  type SkillInstallStep,
  type SkillParseError,
  isSkillMarkdown,
  parseSkillContent,
  parseSkillFile,
  validateSkillMetadata,
} from './skills/index.js';

// LLM Adapters (Phase 4)
export {
  // Core types
  type LLMProvider,
  type LLMProviderConfig,
  type LLMMessage,
  type LLMResponse,
  type LLMStreamChunk,
  type LLMTool,
  type LLMToolCall,
  type LLMUsage,
  type MessageRole,
  type StreamProgressCallback,
  type ToolHandler,
  // Error classes
  LLMProviderError,
  LLMRateLimitError,
  LLMResponseConversionError,
  LLMToolCallError,
  LLMTimeoutError,
  // Response converter
  responseToOutput,
  // LLM Task Executor
  LLMTaskExecutor,
  type LLMTaskExecutorConfig,
  // Provider adapters
  GrokProvider,
  type GrokProviderConfig,
  AnthropicProvider,
  type AnthropicProviderConfig,
  OllamaProvider,
  type OllamaProviderConfig,
} from './llm/index.js';

// Autonomous Agent System
export {
  AutonomousAgent,
  TaskScanner,
  type TaskScannerConfig,
  type Task,
  TaskStatus as AutonomousTaskStatus,
  type TaskFilter,
  type ClaimStrategy,
  type AutonomousTaskExecutor,
  type AutonomousAgentConfig,
  type AutonomousAgentStats,
  type DiscoveryMode,
  type SpeculationConfig,
  VerifierExecutor,
  VerifierLaneEscalationError,
  VERIFIER_METRIC_NAMES,
  extractTaskRiskFeatures,
  scoreTaskRisk,
  allocateVerificationBudget,
  planVerifierSchedule,
  resolveEscalationTransition,
  generateExecutionCandidates,
  detectCandidateInconsistencies,
  arbitrateCandidates,
  type VerifierLaneMetrics,
  type VerifierExecutorConfig,
  type RiskTier,
  type RiskFeatureVector,
  type RiskContribution,
  type TaskRiskScoringContext,
  type TaskRiskScoringConfig,
  type TaskRiskScoreResult,
  type VerificationBudgetDecision,
  type VerifierRouteStrategy,
  type VerifierScheduleInput,
  type VerifierSchedulePlan,
  type EscalationTransitionState,
  type EscalationTransitionReason,
  type EscalationGraphInput,
  type EscalationGraphTransition,
  type GeneratedExecutionCandidate,
  type CandidateGenerationAttemptContext,
  type CandidateGenerationInput,
  type CandidateGenerationResult,
  type CandidateDisagreementReasonCode,
  type CandidateDisagreementReason,
  type CandidateDisagreement,
  type CandidateProvenanceLink,
  type InconsistencyDetectionResult,
  type InconsistencyDetectorInput,
  type CandidateArbitrationScore,
  type CandidateArbitrationDecision,
  type CandidateArbitrationInput,
  type VerifierReason,
  type VerifierVerdict,
  type VerifierVerdictPayload,
  type VerifierInput,
  type TaskVerifier,
  type RevisionInput,
  type RevisionCapableTaskExecutor,
  type VerifierTaskTypePolicy,
  type VerifierAdaptiveRiskWeights,
  type VerifierAdaptiveRiskConfig,
  type MultiCandidateArbitrationWeights,
  type MultiCandidateEscalationPolicy,
  type MultiCandidatePolicyBudget,
  type MultiCandidateConfig,
  type VerifierPolicyConfig,
  type VerifierEscalationMetadata,
  type VerifierLaneConfig,
  type VerifierExecutionResult,
  DefaultClaimStrategy,
} from './autonomous/index.js';

// Eval and deterministic replay
export {
  BENCHMARK_MANIFEST_SCHEMA_VERSION,
  BENCHMARK_ARTIFACT_SCHEMA_VERSION,
  MUTATION_ARTIFACT_SCHEMA_VERSION,
  parseBenchmarkManifest,
  loadBenchmarkManifest,
  hashBenchmarkManifest,
  parseMutationArtifact,
  BenchmarkRunner,
  MutationEngine,
  MutationRunner,
  SeededRandom,
  createDefaultMutationOperators,
  serializeBenchmarkArtifact,
  serializeMutationArtifact,
  writeBenchmarkArtifact,
  writeMutationArtifact,
  evaluateMutationRegressionGates,
  formatMutationGateEvaluation,
  DEFAULT_MUTATION_OPERATOR_IDS,
  DEFAULT_MUTATION_GATE_THRESHOLDS,
  EVAL_TRACE_SCHEMA_VERSION,
  parseTrajectoryTrace,
  migrateTrajectoryTrace,
  canonicalizeTrajectoryTrace,
  stableStringifyJson,
  TrajectoryRecorder,
  TrajectoryReplayEngine,
  projectOnChainEvents,
  computePassAtK,
  computePassCaretK,
  getRewardTier,
  evalRunFromReplayResult,
  computeEvaluationScorecard,
  recordEvaluationMetrics,
  serializeEvaluationScorecard,
  buildCalibrationBins,
  computeExpectedCalibrationError,
  computeMaxCalibrationError,
  computeAgreementRate,
  buildCalibrationReport,
  recordCalibrationMetrics,
  type JsonPrimitive,
  type JsonValue,
  type JsonObject,
  type BenchmarkManifest,
  type BenchmarkScenarioManifest,
  type BenchmarkScenarioRunArtifact,
  type BenchmarkMetricDelta,
  type BenchmarkScenarioReportArtifact,
  type BenchmarkArtifact,
  type BenchmarkScenarioExecutionContext,
  type BenchmarkScenarioExecutionOutput,
  type BenchmarkScenarioRunner,
  type BenchmarkRunnerConfig,
  type BenchmarkRunOptions,
  type MutationOperatorCategory,
  type MutationOperatorContext,
  type MutationOperatorResult,
  type MutationOperator,
  type MutationSelectionOptions,
  type MutationCandidate,
  type MutationEngineConfig,
  type MutationScenarioRunArtifact,
  type MutationOperatorReportArtifact,
  type MutationScenarioReportArtifact,
  type MutationRegressionScenario,
  type MutationArtifact,
  type MutationRunnerConfig,
  type MutationRunOptions,
  type MutationGateThresholds,
  type MutationGateViolation,
  type MutationGateEvaluation,
  type KnownTrajectoryEventType,
  type TrajectoryEventType,
  type TrajectoryRecordInput,
  type TrajectoryRecorderSink,
  type TrajectoryEvent,
  type TrajectoryTrace,
  type LegacyTrajectoryEventV0,
  type LegacyTrajectoryTraceV0,
  type TrajectoryRecorderConfig,
  type ReplayTaskStatus,
  type ReplayTaskState,
  type ReplaySummary,
  type TrajectoryReplayResult,
  type TrajectoryReplayConfig,
  type CanonicalEventTuple,
  type OnChainProjectionInput,
  type ProjectionOptions,
  type ProjectionResult,
  type ProjectionTelemetry,
  type ProjectedTimelineEvent,
  extractCanonicalTuple,
  canonicalizeEvent,
  ANOMALY_CODES,
  ON_CHAIN_TASK_TRANSITIONS,
  ON_CHAIN_DISPUTE_TRANSITIONS,
  ON_CHAIN_TASK_START_STATES,
  ON_CHAIN_DISPUTE_START_STATES,
  EVENT_TO_TASK_STATUS,
  EVENT_TO_DISPUTE_STATUS,
  TransitionValidator,
  validateTransition,
  transitionViolationMessage,
  type ReplayLifecycleType,
  type TransitionValidationViolation,
  type TransitionValidationOptions,
  type TransitionValidationResult,
  type TransitionAnomalyPayload,
  ReplayComparisonService,
  ReplayComparisonError,
  type ReplayAnomaly,
  type ReplayAnomalyCode,
  type ReplayComparisonContext,
  type ReplayComparisonMetrics,
  type ReplayComparisonOptions,
  type ReplayComparisonResult,
  type ReplayComparisonStrictness,
  type ReplayCompareInput,
  parseQueryDSL,
  normalizeQuery,
  applyQueryFilter,
  applyAnomalyFilter,
  QueryDSLParseError,
  type QueryDSL,
  type CanonicalQuery,
  type QueryDSLValidationError,
  type RewardTier,
  type EvalRunRecord,
  type EvalAggregateMetrics,
  type EvaluationScorecard,
  type ScorecardSerializeResult,
  type CalibrationSample,
  type VerdictComparison,
  type CalibrationBin,
  type CalibrationAggregate,
  type CalibrationReport,
} from './eval/index.js';

export {
  InMemoryReplayTimelineStore,
  FileReplayTimelineStore,
  ReplayBackfillService,
  ReplayEventBridge,
  ReplayHealth,
  ReplayTimelineQuery,
  ReplayTimelineStore,
  ReplayTimelineRecord,
  ReplayEventCursor,
  ReplayStorageWriteResult,
  BackfillFetcher,
  BackfillResult,
  type BackfillDuplicateReport,
  type ReplayBridgeConfig,
  type ReplayBridgeBackfillOptions,
  type ReplayBridgeHandle,
  type ReplayBridgeStoreConfig,
  ProjectedTimelineInput,
  BackfillFetcherPage,
  buildReplayKey,
  computeProjectionHash,
  deriveTraceId,
  stableReplayCursorString,
  createReplayAlertDispatcher,
  type ReplayAlertAdapter,
  type ReplayAlertContext,
  type ReplayAnomalyAlert,
  type ReplayAlertingPolicyOptions,
  type ReplayAlertKind,
  type ReplayAlertSeverity,
  ReplayAlertDispatcher,
  REPLAY_ALERT_SCHEMA_VERSION,
  type ReplayAlertSchemaV1,
  REPLAY_ALERT_V1_REQUIRED_FIELDS,
  REPLAY_ALERT_V1_VALID_SEVERITIES,
  REPLAY_ALERT_V1_VALID_KINDS,
  type SchemaCompatibilityResult,
  validateAlertSchema,
  computeAnomalySetHash,
  computeAnomalySetHashFromContexts,
  REPLAY_OPERATIONAL_LIMITS,
  normalizePdaValue,
  normalizePdaString,
  extractDisputePdaFromPayload,
} from './replay/index.js';

// Policy and Safety Engine
export {
  PolicyEngine,
  PolicyViolationError,
  ROLE_PERMISSION_MATRIX,
  isCommandAllowed,
  enforceRole,
  IncidentRoleViolationError,
  InMemoryAuditTrail,
  computeInputHash,
  computeOutputHash,
  type PolicyActionType,
  type PolicyAccess,
  type CircuitBreakerMode,
  type PolicyAction,
  type PolicyBudgetRule,
  type SpendBudgetRule,
  type CircuitBreakerConfig,
  type RuntimePolicyConfig,
  type PolicyViolation,
  type PolicyDecision,
  type PolicyEngineState,
  type PolicyEngineConfig,
  type OperatorRole,
  type IncidentCommandCategory,
  type RolePermission,
  type AuditTrailEntry,
  type AuditTrailStore,
  type AuditTrailVerification,
} from './policy/index.js';

// Tool System (Phase 5)
export {
  // Core types
  type Tool,
  type ToolResult,
  type ToolContext,
  type ToolRegistryConfig,
  type JSONSchema,
  bigintReplacer,
  safeStringify,
  // Error types
  ToolNotFoundError,
  ToolAlreadyRegisteredError,
  ToolExecutionError,
  // Registry
  ToolRegistry,
  // Skill-to-Tool adapter
  skillToTools,
  type ActionSchemaMap,
  type SkillToToolsOptions,
  JUPITER_ACTION_SCHEMAS,
  // Built-in AgenC tools
  createAgencTools,
  createListTasksTool,
  createGetTaskTool,
  createGetTokenBalanceTool,
  createCreateTaskTool,
  createGetAgentTool,
  createGetProtocolConfigTool,
  type SerializedTask,
  type SerializedAgent,
  type SerializedProtocolConfig,
} from './tools/index.js';

// ZK Proof Engine (Phase 7)
export {
  // Core types
  type ProofEngineConfig,
  type ProofCacheConfig,
  type ProofInputs,
  type EngineProofResult,
  type ProofEngineStats,
  type HashResult,
  type ToolsStatus,
  // Error classes
  ProofGenerationError,
  ProofVerificationError,
  ProofCacheError,
  // Cache
  ProofCache,
  deriveCacheKey,
  // Engine
  ProofEngine,
} from './proof/index.js';

// Memory Backends (Phase 6)
export {
  // Core types
  type MemoryBackend,
  type MemoryBackendConfig,
  type MemoryEntry,
  type MemoryRole,
  type MemoryQuery,
  type AddEntryOptions,
  // LLM interop helpers
  entryToMessage,
  messageToEntryOptions,
  // Error classes
  MemoryBackendError,
  MemoryConnectionError,
  MemorySerializationError,
  MemoryEncryptionError,
  // Durability
  type DurabilityLevel,
  type DurabilityInfo,
  MEMORY_OPERATIONAL_LIMITS,
  // Encryption
  type EncryptionConfig,
  type EncryptionProvider,
  createAES256GCMProvider,
  // In-memory backend
  InMemoryBackend,
  type InMemoryBackendConfig,
  // SQLite backend
  SqliteBackend,
  type SqliteBackendConfig,
  // Redis backend
  RedisBackend,
  type RedisBackendConfig,
  // Memory graph
  MemoryGraph,
  type ProvenanceSourceType,
  type ProvenanceSource,
  type MemoryEdgeType,
  type MemoryGraphNode,
  type MemoryGraphEdge,
  type UpsertMemoryNodeInput,
  type AddMemoryEdgeInput,
  type MemoryGraphQuery,
  type MemoryGraphResult,
  type MemoryGraphConfig,
  type CompactOptions,
} from './memory/index.js';

// Dispute Operations (Phase 8)
export {
  // Enums
  OnChainDisputeStatus,
  // Constants
  DISPUTE_STATUS_OFFSET,
  DISPUTE_TASK_OFFSET,
  // Functions
  parseOnChainDispute,
  parseOnChainDisputeVote,
  disputeStatusToString,
  // PDA derivation
  deriveDisputePda,
  findDisputePda,
  deriveVotePda,
  findVotePda,
  // Error classes
  DisputeNotFoundError,
  DisputeVoteError,
  DisputeResolutionError,
  DisputeSlashError,
  // Operations class
  DisputeOperations,
  // Types
  type OnChainDispute,
  type OnChainDisputeVote,
  type InitiateDisputeParams,
  type VoteDisputeParams,
  type ResolveDisputeParams,
  type ExpireDisputeParams,
  type ApplySlashParams,
  type DisputeResult,
  type VoteResult,
  type DisputeOpsConfig,
} from './dispute/index.js';

// Workflow DAG Orchestrator (Phase 9)
export {
  // Enums
  OnChainDependencyType,
  WorkflowNodeStatus,
  WorkflowStatus,
  // Types
  type TaskTemplate,
  type WorkflowEdge,
  type WorkflowDefinition,
  type WorkflowConfig,
  type WorkflowNode,
  type WorkflowState,
  type WorkflowStats,
  type WorkflowCallbacks,
  type DAGOrchestratorConfig,
  // Error classes
  WorkflowValidationError,
  WorkflowSubmissionError,
  WorkflowMonitoringError,
  WorkflowStateError,
  // Validation
  validateWorkflow,
  topologicalSort,
  // Goal compiler
  GoalCompiler,
  estimateWorkflow,
  type GoalPlannerInput,
  type PlannerTaskDraft,
  type PlannerWorkflowDraft,
  type GoalPlanner,
  type GoalCompileRequest,
  type GoalCompileWarning,
  type WorkflowDryRunEstimate,
  type GoalCompileResult,
  type GoalCompilerDefaults,
  type GoalCompilerConfig,
  // Optimizer contracts
  WORKFLOW_FEATURE_SCHEMA_VERSION,
  WORKFLOW_OBJECTIVE_SCHEMA_VERSION,
  createDefaultWorkflowObjectiveSpec,
  validateWorkflowObjectiveSpec,
  scoreWorkflowObjective,
  workflowObjectiveOutcomeFromFeature,
  parseWorkflowFeatureVector,
  type WorkflowRunOutcome,
  type WorkflowTopologyFeatures,
  type WorkflowCompositionFeatures,
  type WorkflowNodeFeature,
  type WorkflowOutcomeLabels,
  type WorkflowFeatureVector,
  type LegacyWorkflowFeatureVectorV0,
  type WorkflowObjectiveMetric,
  type WorkflowObjectiveWeight,
  type WorkflowObjectiveSpec,
  type WorkflowObjectiveOutcome,
  // Feature extraction
  WORKFLOW_TELEMETRY_KEYS,
  extractWorkflowFeatureVector,
  extractWorkflowFeatureVectorFromCollector,
  type WorkflowFeatureExtractionOptions,
  // Mutation + optimizer + rollout
  generateWorkflowMutationCandidates,
  WorkflowOptimizer,
  WorkflowCanaryRollout,
  type WorkflowMutationOperator,
  type WorkflowMutationRecord,
  type WorkflowMutationCandidate,
  type WorkflowMutationConfig,
  type WorkflowOptimizerRuntimeConfig,
  type WorkflowOptimizerConfig,
  type WorkflowOptimizationInput,
  type WorkflowCandidateScore,
  type WorkflowOptimizationAuditEntry,
  type WorkflowOptimizationResult,
  type WorkflowRolloutStopLossThresholds,
  type WorkflowRolloutConfig,
  type WorkflowRolloutSample,
  type WorkflowRolloutVariantStats,
  type WorkflowRolloutDeltas,
  type WorkflowRolloutAction,
  type WorkflowRolloutReason,
  type WorkflowRolloutDecision,
  // Classes
  DAGSubmitter,
  DAGMonitor,
  DAGOrchestrator,
} from './workflow/index.js';

// Team Contracts (Phase 12)
export {
  TeamContractValidationError,
  TeamContractStateError,
  TeamPayoutError,
  TeamWorkflowTopologyError,
  InMemoryTeamAuditStore,
  type TeamAuditStore,
  type InMemoryTeamAuditStoreConfig,
  TeamContractEngine,
  type TeamContractEngineConfig,
  type TeamContractEngineReadonlyView,
  type CreateTeamContractInput,
  type JoinTeamContractInput,
  type AssignTeamRoleInput,
  type CompleteTeamCheckpointInput,
  type FailTeamCheckpointInput,
  type FinalizeTeamPayoutInput,
  type CancelTeamContractInput,
  TeamWorkflowAdapter,
  type TeamWorkflowBuildOptions,
  type TeamWorkflowBuildResult,
  type TeamWorkflowLaunchResult,
  computeTeamPayout,
  type TeamPayoutComputationInput,
  canonicalizeTeamId,
  validateTeamId,
  MAX_TEAM_ID_LENGTH,
  TEAM_ID_PATTERN,
  type TeamContractStatus,
  type TeamCheckpointStatus,
  type TeamRoleTemplate,
  type TeamCheckpointTemplate,
  type TeamPayoutConfig,
  type FixedTeamPayoutConfig,
  type WeightedTeamPayoutConfig,
  type MilestoneTeamPayoutConfig,
  type TeamTemplate,
  type TeamMemberInput,
  type TeamMember,
  type TeamCheckpointState,
  type TeamPayoutResult,
  type TeamAuditEventType,
  type TeamAuditEvent,
  type RoleFailureAttribution,
  type TeamContractSnapshot,
  type TeamEngineHooks,
} from './team/index.js';

// Marketplace Bidding (Phase 13)
export {
  MarketplaceValidationError,
  MarketplaceStateError,
  MarketplaceAuthorizationError,
  MarketplaceMatchingError,
  selectWinningBid,
  rankTaskBids,
  computeWeightedScore,
  TaskBidMarketplace,
  ConservativeBidStrategy,
  BalancedBidStrategy,
  AutonomousBidder,
  type BidStrategy,
  type BidStrategyContext,
  type ConservativeBidStrategyConfig,
  type BalancedBidStrategyConfig,
  type AutonomousBidderConfig,
  type PlaceBidOptions,
  type MarketplaceMutationInput,
  type CreateTaskBidRequest,
  type UpdateTaskBidRequest,
  type CancelTaskBidRequest,
  type SelectTaskBidRequest,
  type ListTaskBidsRequest,
  type AcceptTaskBidRequest,
  type AutoMatchTaskBidRequest,
  type SetTaskOwnerRequest,
  type TaskBidMarketplaceConfig,
  type TaskBidBookSnapshot,
  type AcceptTaskBidResult,
  type RankedTaskBid,
  type BidStatus,
  type MatchingPolicy,
  type WeightedScoreWeights,
  type MatchingPolicyConfig,
  type BidRateLimitConfig,
  type BidAntiSpamConfig,
  type TaskBidInput,
  type TaskBidUpdateInput,
  type TaskBid,
  type TaskBidBookState,
  type WeightedScoringBreakdown,
  type TaskBidSelection,
} from './marketplace/index.js';

// Connection Manager
export {
  // Types
  type EndpointConfig,
  type RetryConfig,
  type HealthCheckConfig,
  type ConnectionManagerConfig,
  type EndpointHealth,
  type ConnectionManagerStats,
  // Error classes
  ConnectionError,
  AllEndpointsUnhealthyError,
  // Utilities
  isRetryableError,
  isConnectionLevelError,
  isWriteMethod,
  computeBackoff,
  deriveCoalesceKey,
  // Class
  ConnectionManager,
} from './connection/index.js';

// Telemetry (Phase 11)
export {
  // Core types
  type TelemetryCollector,
  type TelemetrySnapshot,
  type TelemetrySink,
  type TelemetryConfig,
  // Collector implementations
  UnifiedTelemetryCollector,
  NoopTelemetryCollector,
  // Built-in sinks
  ConsoleSink,
  CallbackSink,
  // Error class
  TelemetryError,
  // Metric name constants
  TELEMETRY_METRIC_NAMES,
} from './telemetry/index.js';

// Gateway (Phase 1)
export {
  Gateway,
  ConfigWatcher,
  getDefaultConfigPath,
  loadGatewayConfig,
  validateGatewayConfig,
  isValidGatewayConfig,
  diffGatewayConfig,
  GatewayValidationError,
  GatewayConnectionError,
  GatewayStateError,
  GatewayLifecycleError,
  type GatewayConfig,
  type GatewayLLMConfig,
  type GatewayMemoryConfig,
  type GatewayChannelConfig,
  type GatewayAgentConfig,
  type GatewayConnectionConfig,
  type GatewayLoggingConfig,
  type GatewayBindConfig,
  type GatewayState,
  type GatewayStatus,
  type GatewayEvent,
  type GatewayEventHandler,
  type GatewayEventSubscription,
  type GatewayOptions,
  type ControlMessage,
  type ControlMessageType,
  type ControlResponse,
  type ChannelHandle,
  type ConfigDiff,
  type ConfigReloadCallback,
  type ConfigErrorCallback,
  // Message types (Phase 1.2)
  createGatewayMessage,
  createOutboundMessage,
  validateGatewayMessage,
  validateOutboundMessage,
  validateAttachment,
  type GatewayMessage,
  type OutboundMessage,
  type MessageAttachment,
  type MessageScope,
  type CreateGatewayMessageParams,
} from './gateway/index.js';

// Agent Builder (Phase 10)
export { AgentBuilder, BuiltAgent } from './builder.js';
