#!/usr/bin/env node
/**
 * Prebuild script: Copy IDL and types from Anchor build output
 *
 * This script copies:
 * - target/idl/agenc_coordination.json -> runtime/idl/
 * - target/types/agenc_coordination.ts -> runtime/src/types/ (with DO NOT EDIT header)
 *
 * Run automatically via `npm run prebuild` before builds.
 */

const fs = require('fs');
const path = require('path');

// Paths relative to runtime/ directory
const RUNTIME_DIR = path.dirname(__dirname);
const ROOT_DIR = path.dirname(RUNTIME_DIR);

const IDL_SOURCE = path.join(ROOT_DIR, 'target', 'idl', 'agenc_coordination.json');
const IDL_DEST_DIR = path.join(RUNTIME_DIR, 'idl');
const IDL_DEST = path.join(IDL_DEST_DIR, 'agenc_coordination.json');

const TYPES_SOURCE = path.join(ROOT_DIR, 'target', 'types', 'agenc_coordination.ts');
const TYPES_DEST_DIR = path.join(RUNTIME_DIR, 'src', 'types');
const TYPES_DEST = path.join(TYPES_DEST_DIR, 'agenc_coordination.ts');

// Header to prepend to copied types file
const TYPES_HEADER = `/* eslint-disable */
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npm run prebuild (scripts/copy-idl.js)
// Source: target/types/agenc_coordination.ts
// To regenerate: anchor build && npm run prebuild

`;

function main() {
  console.log('Copying IDL and types from Anchor build output...');

  // Check that source files exist
  if (!fs.existsSync(IDL_SOURCE)) {
    console.error(`Error: IDL not found at ${IDL_SOURCE}`);
    console.error('Run "anchor build" first to generate the IDL.');
    process.exit(1);
  }

  if (!fs.existsSync(TYPES_SOURCE)) {
    console.error(`Error: Types file not found at ${TYPES_SOURCE}`);
    console.error('Run "anchor build" first to generate the types.');
    process.exit(1);
  }

  // Create destination directories
  try {
    fs.mkdirSync(IDL_DEST_DIR, { recursive: true });
    fs.mkdirSync(TYPES_DEST_DIR, { recursive: true });
  } catch (err) {
    console.error(`Error: Failed to create destination directories.`);
    console.error(`  ${err.message}`);
    process.exit(1);
  }

  // Copy IDL JSON file
  if (fs.existsSync(IDL_DEST)) {
    console.log(`  Warning: Overwriting existing ${IDL_DEST}`);
  }
  try {
    fs.copyFileSync(IDL_SOURCE, IDL_DEST);
  } catch (err) {
    console.error(`Error: Failed to copy IDL file to ${IDL_DEST}`);
    console.error(`  ${err.message}`);
    process.exit(1);
  }
  console.log(`  Copied: ${IDL_SOURCE} -> ${IDL_DEST}`);

  // Copy types file with header prepended
  if (fs.existsSync(TYPES_DEST)) {
    console.log(`  Warning: Overwriting existing ${TYPES_DEST}`);
  }
  try {
    const typesContent = fs.readFileSync(TYPES_SOURCE, 'utf8');
    fs.writeFileSync(TYPES_DEST, TYPES_HEADER + typesContent);
  } catch (err) {
    console.error(`Error: Failed to copy types file to ${TYPES_DEST}`);
    console.error(`  ${err.message}`);
    process.exit(1);
  }
  console.log(`  Copied: ${TYPES_SOURCE} -> ${TYPES_DEST} (with DO NOT EDIT header)`);

  console.log('Done.');
}

main();
