import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

interface ToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function assertToolDefinition(value: unknown, index: number): asserts value is ToolDefinition {
  if (!isRecord(value)) {
    throw new Error(`desktop tool definition at index ${index} was not an object`);
  }
  if (typeof value.name !== "string" || value.name.length === 0) {
    throw new Error(`desktop tool definition at index ${index} is missing a valid name`);
  }
  if (typeof value.description !== "string" || value.description.length === 0) {
    throw new Error(
      `desktop tool definition "${value.name}" is missing a valid description`,
    );
  }
  if (!isRecord(value.inputSchema)) {
    throw new Error(
      `desktop tool definition "${value.name}" is missing a valid inputSchema`,
    );
  }
}

function normalizeLineEndings(value: string): string {
  return value.replace(/\r\n/g, "\n");
}

async function loadDesktopToolDefinitions(
  serverModulePath: string,
): Promise<readonly ToolDefinition[]> {
  const serverModule = (await import(pathToFileURL(serverModulePath).href)) as {
    TOOL_DEFINITIONS?: unknown;
  };
  const rawToolDefinitions = serverModule.TOOL_DEFINITIONS;
  if (!Array.isArray(rawToolDefinitions)) {
    throw new Error("desktop server TOOL_DEFINITIONS export was not an array");
  }
  rawToolDefinitions.forEach((toolDefinition, index) =>
    assertToolDefinition(toolDefinition, index),
  );
  return rawToolDefinitions;
}

function renderToolDefinitions(toolDefinitions: readonly ToolDefinition[]): string {
  const serialized = JSON.stringify(toolDefinitions, null, 2);
  return `/**
 * AUTO-GENERATED FROM ../../containers/desktop/server/src/tools.ts
 * BY \`npm --prefix runtime run generate:desktop-tool-definitions\`.
 *
 * Do not edit this file manually. Update the desktop server TOOL_DEFINITIONS
 * export instead and re-run the generator.
 *
 * @module
 */

export interface DesktopToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
}

export const TOOL_DEFINITIONS: DesktopToolDefinition[] = ${serialized};
`;
}

async function readExistingOutput(outputPath: string): Promise<string> {
  try {
    return await readFile(outputPath, "utf8");
  } catch (error) {
    if (isRecord(error) && error.code === "ENOENT") {
      return "";
    }
    throw error;
  }
}

function reportDriftAndExit(): void {
  process.stderr.write(
    [
      "runtime/src/desktop/tool-definitions.ts is out of sync with",
      "containers/desktop/server/src/tools.ts.",
      "Run `npm --prefix runtime run generate:desktop-tool-definitions` and commit the result.",
      "",
    ].join(" "),
  );
  process.exitCode = 1;
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const runtimeDir = resolve(scriptDir, "..");
  const serverModulePath = resolve(
    runtimeDir,
    "../containers/desktop/server/src/tools.ts",
  );
  const outputPath = resolve(runtimeDir, "src/desktop/tool-definitions.ts");
  const toolDefinitions = await loadDesktopToolDefinitions(serverModulePath);
  const nextContent = renderToolDefinitions(toolDefinitions);
  const existingContent = await readExistingOutput(outputPath);

  if (normalizeLineEndings(existingContent) === nextContent) {
    if (!checkOnly) {
      process.stdout.write("runtime desktop tool definitions already up to date\n");
    }
    return;
  }

  if (checkOnly) {
    reportDriftAndExit();
    return;
  }

  await writeFile(outputPath, nextContent, "utf8");
  process.stdout.write(`updated ${outputPath}\n`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.stack ?? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
